name: Setup QEMU binfmt
description: Setup QEMU binfmt
runs:
  using: 'composite'
  steps:
    run: |
      export DEBIAN_FRONTEND=noninteractive
      sudo apt-get update
      sudo apt-get install -y binfmt-support qemu-user-static
