name: Setup QEMU emulation
description: Setup QEMU emulation
runs:
  using: composite
  steps:
    - name: Setup QEMU emulation
      shell: bash
      run: |
        $GITHUB_ACTION_PATH/setup-qemu-emulation.sh
